#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 🌸 🌸 🌸 🌸 🌸 🌸 🌸 🌸 🌸 🌸

bspc config border_width         1
bspc config window_gap           4

bspc config split_ratio          .58
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Color
bspc config normal_border_color '#090618'
bspc config focused_border_color '#dcd7ba'
bspc config presel_border_color '#FFDB91'
bspc config normal_sticky_border_color '#282A2E'
bspc config focused_sticky_border_color '#83a598'
bspc config urgent_border_color '#F28B82'

exec nitrogen --restore &
exec picom &
exec xrandr -s 1920x1080 -r 165 &
exec ~/.config/polybar/launch.sh
